{
    "batch_size": 64,
    "steps": 50000,
    "save_freq": 5000,
    "log_freq": 100,
    "eval_freq": 1000,
    "dataset": {
        "repo_id": "danielsanjosepro/organize_drawer_v1"
    },
    "policy": {
        "repo_id": "danielsanjosepro/unet_meanflow_organize_drawer_v1",
        "type": "unet_meanflow",
        "optimizer_lr": 1e-4,
        "use_meanflow": false,
        "do_multi_step_sampling": true
    },
    "wandb": {
        "enable": true,
        "project": "master_thesis"
    }
}
