{
    "batch_size": 64,
    "steps": 20000,
    "save_freq": 5000,
    "log_freq": 100,
    "eval_freq": 500,
    "dataset": {
        "repo_id": "lerobot/pusht"
    },
    "env": "pusht",
    "policy": {
        "repo_id": "danielsanjosepro/ditmeanflow_pusht_v1",
        "type": "ditflow",
    },
    "wandb": {
        "enable": true,
        "project": "master_thesis"
    }
}

